# Generated by Django 2.0 on 2017-12-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleprofile',
            name='sub_model',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
